theme: jekyll-theme-cayman
title: Epic Poetry Club
description:  Appreciating english language epic poetry
url: https://epicpoetryclub.supertestnet.org
author: Venato Verba
header_pages:
  - posts.md
  - file_maker.html
plugins:
  - jekyll-feed
