theme: jekyll-theme-cayman
title: Venato Verba
description:  Lover of epic poetry
url: https://venatoverba.com
author: Venato Verba
header_pages:
  - posts.md
  - file_maker.html
  - download_page.html
  - buy_with_bitcoin.html
plugins:
  - jekyll-feed
